stack_overflow/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackoverflow.urls')),
    path('', include('user.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackoverflow/urls.py
from django.urls import path
from . import views

app_name = 'stack_overflow'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.HomeView, name='home'),
    path('about/', views.AboutView, name='about'),
    path('questions/', views.QuestionListView.as_view(), name="question-lists"),
    path('questions/create', views.QuestionCreateView.as_view(), name="question-create"),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name="question-detail"),
]

user/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

app_name = 'user'

urlpatterns = [
    path('register/', views.Register, name="register"),
    path('profile/', views.Profile, name="profile"),
    path('profile_update/', views.ProfileUpdate, name="profile_update"),
    path('login/', auth_view.LoginView.as_view(template_name="user/login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="user/logout.html"), name='logout'),


]

stackoverflow/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=10000)
    # content = models.TextField(null=True, blank=True)
    content = RichTextField()
    likes = models.ManyToManyField(User, related_name='question_post')
    date_created = models.DateTimeField(default=timezone.now)   
    
    def __str__(self):
        return f'{self.user.username} - Question'
    
    def get_absolute_url(self):
        return reverse('stack_overflow:question-detail', kwargs={'pk':self.pk})
    
    def total_likes(self):
        return self.likes.count()

class Comment(models.Model):
    question = models.ForeignKey(Question, related_name="comment", on_delete=models.CASCADE)
    name = models.CharField(max_length=1000)
    content = RichTextField()
    date_created = models.DateTimeField(default=timezone.now)   

    def __str__(self):
        return '%s - %s' % (self.question.title, self.question.user)

    def get_success_url(self):
        return reverse('stack_overflow:question-detail', kwargs={'pk':self.pk})
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

user/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=1000)
    phone = models.IntegerField(null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to="profile_pic")

    def __str__(self):
        return f'{self.user.username} - Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

stackoverflow/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'content']

        widgets = {
            'name': forms.TextInput(
                attrs={
                    'placeholder': 'Nombre Categoría',
                    'class': 'form-control form-control-md',
                    'autofocus': True
                }
            ),
            'body': forms.Textarea(attrs={'class': 'form-control form-control-lg'}),
        }

user/forms.py
from django import forms
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):

    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Enter Email', "class": "a custom class form-control form-control-md"
    }))
    

    email = models.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    
    class Meta:
        model = User
        fields = ['username', 'email']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'phone', 'image']

stackoverflow/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView, DetailView, CreateView
from .models import *
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.urls import reverse, reverse_lazy

from .forms import CommentForm


# Create your views here.


def index(request):
    return render(request, 'index.html')


def HomeView(request):
    return render(request, 'home.html')

def AboutView(request):
    return render(request, 'about.html')

#CRUD Functions
class QuestionListView(ListView):
    model = Question
    context_object_name = 'questions'
    ordering = ['-date_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['questions'] = context['questions'].filter(title__icontains = search_input)
            context['search_input'] = search_input
        return context

class QuestionDetailView(DetailView):
    model = Question

    def get_context_data(self, *args, **kwargs):
        context = super(QuestionDetailView, self).get_context_data()
        something = get_object_or_404(Question, id=self.kwargs['pk'])
        total_likes = something.total_likes()
        liked = False
        if something.likes.filter(id=self.request.user.id).exists():
            liked = True

        context['total_likes'] = total_likes
        context['liked'] = liked
        return context
    

class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['title', 'content']
    context_object_name =  'question'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from .forms import UserRegisterForm
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, UserUpdateForm
# Create your views here.


def Register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Account successfully created for {username}! Login In now")
            return redirect('stack_overflow:home')
    else:
        form = UserRegisterForm()
    return render(request, 'user/register.html', {'form': form})

@login_required
def Profile(request):
        return render(request, 'user/profile.html')

@login_required
def ProfileUpdate(request):
     if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid():
             u_form.save()
             p_form.save()
             messages.success(request, f'Account Updated Successfully')
             return redirect('profile')
        else:
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
     context = {
          'u_form': u_form,
          'p_form': p_form
     }

     return render(request, 'user/profile_update.html', context)

stackoverflow/templates/stackoverflow/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        /* .list-question{
            height: 400px;
            background-color: rgb(255, 219, 173);
        } */
        #fh3{
            text-align: center;
            font-size: 30px;
            padding-top: 20px;
            text-align: left;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }
        #fh6{
            text-align: left;
            font-size: 15px;
            /* padding-top: 20px; */
            padding-bottom: 20px;
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: left;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <!-- <h1 id="fh1">Hey Guys, Let's help :)</h1> -->
            <!-- <button class="btn" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button> -->

            <!-- <div style="margin-top: 55px;">
                <button class="btn btn-primary" id="logout-btn"><a id="fa" href="" style="color: white; text-decoration: none;">Ask Question</a></button>
            </div> -->
        </div>
        <div class="list-question">
            <div class="questions">
                <div class="container" style="background-color: rgba(255, 235, 209, 0.808); padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    <h3 id="fh3">{{question.title}}</h3>
                    <hr>
                    <h6 id="fh6">{{ question.content|safe }}</h6>
                    <hr>
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155); text-align: right;">Asked By: <a href="{% url 'user:profile' %}">{{ object.user|title }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{ object.date_created|date:"j F, Y" }}</h6>
                    <br>
                        <form action="" method="POST">
                            {% csrf_token %}
                            {% if user.is_authenticated %}
                                {% if liked %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% else %}
                                    <div style="display: flex; align-items: center; margin-left: 10px;">
                                        <button type="submit" name="question_id" value="{{ question.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                                    </div>
                                {% endif %}
                            {% else %}
                                <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                            {% endif %}

                        </form>
                    <br>
                    <h2>Answers...</h2> <br><br><br>

                    {% if not question.comment.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}
                        {% for comment in question.comment.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - On: {{comment.date_created|date:"j F, Y"}}</i></h3>
                            <hr>  
                        {% endfor %}
                    {% endif %}



                    <!-- {% if not questions.comments.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}

                        {% for comment in questions.comments.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.body|safe}}</h3>
                            <h3 style="font-size: 10px;">Answered by: <i><a href="">{{comment.name}}</a> - {{comment.date_added|date:"j F, Y"}}</i></h3>
                            <hr>    
                        {% endfor %}
                    {% endif %}

                    <br><br><br><br><br><br>

                    <form action="" method="POST">
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                        {% if liked %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 60px;"><img src="https://image.similarpng.com/very-thumbnail/2020/06/Dislike-icon-transparent-PNG.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% else %}
                            <div style="display: flex; align-items: center; margin-left: 10px;">
                                <button type="submit" name="questions_id" value="{{ questions.id }}" style="border: none; border-radius: 30px;"><img src="https://i.pinimg.com/originals/39/44/6c/39446caa52f53369b92bc97253d2b2f1.png" alt="" style="width: 40px;"></button> <h5 style="margin-left: 10px; cursor: pointer;"> |  {{ total_likes }} Likes</h5>
                            </div>
                        {% endif %}
                        {% else %}
                            <h5 style="margin-left: 10px; cursor: pointer;"><a href="{% url 'login' %}">Login</a> to Like Question |  {{ total_likes }} Likes</h5>
                        {% endif %}
                    </form> -->
                    
                    <a class="btn btn-outline-primary" id="fa" href="" style="text-decoration: none;">Answer Question</a>
                    <a style="text-decoration: none; " class="btn btn-outline-success" href="">&#x270E;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-danger" href="">&#x2716;</a>
                    <a style="text-decoration: none; " class="btn btn-outline-secondary" href="">&#x21a9;</a>
                </div> <br><br>
                    <!-- Answer Section -->
                
                </div> <br>
            </div>
        </div>
        <br>
        
    </div>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script> -->
</body>
</html>
{% endblock content %}

stackoverflow/templates/stackoverflow/question_list.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
            /* padding-bottom: 20px; */
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        a{
            color: rgb(0, 132, 255);
        }
        a:hover{
            text-decoration: none;
            color: darkblue;
            
        }
        h5{
            color: rgb(133, 133, 133);
        }
    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
            <h1 id="fh1">Top Questions</h1>
            {% if user.is_authenticated %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url "stack_overflow:question-create" %}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {% else %}
            <button class="btn" id="logout-btn"><a id="fa" href="{% url 'user:login' %}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {% endif %}
        </div>
        <br><br>
        <div class="list-question">
            <div class="questions">
                {% for question in questions %}
                <div class="container" style="background: linear-gradient(to right, rgb(255, 226, 182), rgba(255, 166, 0, 0.027)); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                    <div id="title-sec" style="display: flex; align-items: center;">
                        <a href="{% url 'user:profile' %}"><img src="{{ request.user.profile.image.url }}" style="width: 50px;"></a></img>
                        <h3 id="fh3"><a href="{% url 'stack_overflow:question-detail' question.id %}">{{ question.title }}</a></h3>
                    </div>
                    <hr>
                    {% if question.content|wordcount <= 10 %}
                    <h6 id="fh6" style="text-align: left;">{{ question.content}}</h6>
                    {% else %}
                    <h6 id="fh6" style="text-align: left;">{{ question.content|truncatewords:10}}/ <a href="{% url 'stack_overflow:question-detail' question.id %}">Read More</a></h6>
                    {% endif %}
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155);">Asked By: <a href="{% url 'user:profile' %}">{{ question.user }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{question.date_created|date:"j F, Y"}}</h6>
                    <h5 style="text-align: right; font-size: 12px; font-style: italic;">Tags</h5>
                </div> <br>
                {% endfor %}
            </div>
        </div>   
    </div>
    <br>
    <br>
    <br>
</body>
</html>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>


    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Stack Overflow - Where Developers Learn, Share, &amp; Build Careers</title>
    <link rel="shortcut icon" href='https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196'>
    <link rel="apple-touch-icon" href='https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a'>
    <link rel="image_src" href='https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a'>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css' />
    <!-- <link rel="stylesheet" href="assets/css/main.css"> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'img/stackoverflow.png' %}"/>
</head>
<body>
    {% include 'partials/header.html' %}
    {% block content %}
      
    {% endblock  %}
    {% include 'partials/section.html' %}

    {% include 'partials/footer.html' %}
    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}


{% block title %}
Index
{% endblock  %}

{% block content %}
<h1>Hello World!</h1>
{% endblock  %}

templates/partials/header.html
{% load static %}



{% block content %}

    <header>
        <div class="nav-container">
            <nav>
                <div class="nav-brand">
                    <div class="hamburger-menu-container">
        
                        <div class="hamburger-menu">
                            <div class="line"></div>
                            <div class="line"></div>
                            <div class="line"></div>
                        </div>
                        <div class="nav-dropdown-menu">
                            <a href="{% url "stack_overflow:home" %}" class="current-link">Home</a>
                            <h5>Public</h5>
                            <ul class="nav-ul">
                                <li class="nav-item">
                                    <!--<i class="fas fa-globe-europe"></i>-->
                                    
                                    <a href="{% url "stack_overflow:home" %}" class="nav-link"><i class="fab fa-stack-overflow"></i> Stack Overflow</a>
                                </li>
                                <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-tag"></i> Tags</a></li>
                                <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-user"></i> Users</a></li>
                            </ul>
                            <h5>Find a Job</h5>
                            <ul class="nav-ul">
                                <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-suitcase"></i> Jobs</a></li>
                                <li class="nav-item"><a href="#" class="nav-link"><i class="fas fa-building"></i> Companies</a></li>
                            </ul>
                            <h5>Teams <a href="#" >What's this ?</a></h5>
                            <a href="#" class="nav-link">
                                <i class="fas fa-briefcase"></i>
                                <span>Free 30 Day Trial</span>
                            </a>
                        </div>
                    </div>
        
                    <a href="" class="nav-icon">
                        <i class="fab fa-stack-overflow"></i>
                        <a href="{% url "stack_overflow:home" %}" style="text-decoration: none; color: black;"><div class="nav-icon-text">Stack <span class="nav-bold-text">Overflow</span></a>
                        <!-- <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span> -->
        
                        
                        </div>
                    </a>
                </div>
                <div class="nav-base-links">
                    <ul>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Products</a></li>
                        <li><a href="#">For Teams</a></li>
                    </ul>
                </div>
                <div class="nav-search">
                    <div class="search-container">
                        <i class="fas fa-search"></i>
                        <form action="" method="GET">
                            <input type="text" id="" name="search-area" placeholder="Search...">
                            <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                        </form>
                    </div>
                    <div class="search-hints">
                        <div class="search-arrow-up"></div>
                        <div class="search-hint-body">
                            <div class="hints-grid-column">
                                <div class="hint-text"><span>[tag] </span> search within a tag</div>
                                <div class="hint-text"><span>user:1234 </span>  search by author</div>
                                <div class="hint-text"><span>"words here"</span> exact phrase </div>
                            </div>
                            <div class="hints-grid-column">
                                <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                                <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                            </div>
                        </div>
                        <div class="search-hint-footer">
                            <a href="#" class="btn">Ask a question</a>
                            <a href="#" class="search-help">Search help</a>
                        </div>
                    </div>
        
                </div>
                <div class="nav-right-buttons">
                    <div class="search-btn">
                        <i class="fas fa-search"></i>
                    </div>
                    {% if user.is_authenticated %}
                    <a href="{% url "user:profile" %}" class="btn btn-login">Profile</a>
                    <a href="{% url "user:logout" %}" class="btn btn-register">Logout</a> 
                    {% else %}
                    <a href="{% url "user:login" %}" class="btn btn-login">Log in</a>
                    <a href="{% url "user:register" %}" class="btn btn-register">Sign up</a> 
                    {% endif %}
                </div>
            </nav>
        </div>

        <div style+"margin-top: 10px;">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <h4 style="text-align:center;">{{ message }}</h4>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

    </header>

{% endblock  %}